[package]
name = "bmp5xx-spi"
version = "0.1.0"
edition = "2024"
authors = ["AVS Origami <avs.origami@gmail.com>"]
readme = "readme"
license = "BSD-3-Clause"

keywords = [
    "async",
    "embedded-hal",
    "pressure",
    "sensor",
]

categories = [
    "embedded",
    "no-std::no-alloc",
    "hardware-support",
]

[dependencies]
byteorder = { version = "1.5.0", default-features = false }
embedded-hal-async = "1.0.0"